name: gnome-text-editor-local-deb
base: core24
grade: stable
confinement: strict
summary: GNOME's Text Editor
description: GNOME's Text Editor, from local binary .deb file, only for one architecture given by the .deb file, not suitable for Snap Store. To be used to quickly prepare a proprietary .deb for use in an all-Snap distro.
version: "46.3"

slots:
  # for GtkApplication registration
  gnome-text-editor:
    interface: dbus
    bus: session
    name: org.gnome.TextEditor

layout:
  /usr/share/gnome-text-editor:
    bind: $SNAP/usr/share/gnome-text-editor

apps:
  gnome-text-editor:
    extensions: [gnome]
    command: usr/bin/gnome-text-editor
    desktop: usr/share/applications/org.gnome.TextEditor.desktop
    common-id: org.gnome.TextEditor.desktop
    environment:
      GTK_USE_PORTAL: "1"
      GDK_DEBUG: "portals"
    plugs:
      - home
      - removable-media
      - mount-observe
      - cups

parts:
  gnome-text-editor:
    plugin: dump
    # Download with "apt download gnome-text-editor" (on Jammy) or download from
    # https://launchpad.net/ubuntu/+source/gnome-text-editor/ for
    # the needed version and architecture before building the Snap
    source: gnome-text-editor_46.3-0ubuntu2_amd64.deb
    source-type: deb

  libraries:
    after: [ gnome-text-editor ]
    plugin: nil
    stage-packages:
      - libeditorconfig0
    prime:
      - usr/lib/*/libeditorconfig.so.*
