name: gnome-text-editor-stage-packages
base: core22
grade: stable
confinement: strict
summary: GNOME's Text Editor
description: GNOME's Text Editor, from binary .deb file from package repository, buildable for all architectures, will be built for all architectures when put into the Snap Store. Method for quick snapping of software available in a package repository and putting it into the Snap Store.
version: "42.2"

# this is not used or needed for anything other than to trigger automatic
# installation of the cups snap via "default-provider: cups"
plugs:
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo

slots:
  # for GtkApplication registration
  gnome-text-editor:
    interface: dbus
    bus: session
    name: org.gnome.TextEditor

layout:
  /usr/share/gnome-text-editor:
    bind: $SNAP/usr/share/gnome-text-editor

apps:
  gnome-text-editor:
    extensions: [gnome]
    command: usr/bin/gnome-text-editor
    desktop: usr/share/applications/org.gnome.TextEditor.desktop
    common-id: org.gnome.TextEditor.desktop
    plugs:
      - gsettings
      - mount-observe
      - cups
      - home

parts:
  gnome-text-editor:
    plugin: nil
    source: .
    stage-packages:
     - gnome-text-editor
