name: gnome-text-editor-stage-packages
base: core24
grade: stable
confinement: strict
summary: GNOME's Text Editor
description: GNOME's Text Editor, from binary .deb file from package repository, buildable for all architectures, will be built for all architectures when put into the Snap Store. Method for quick snapping of software available in a package repository and putting it into the Snap Store.
version: "46.3"

slots:
  # for GtkApplication registration
  gnome-text-editor:
    interface: dbus
    bus: session
    name: org.gnome.TextEditor

layout:
  /usr/share/gnome-text-editor:
    bind: $SNAP/usr/share/gnome-text-editor

apps:
  gnome-text-editor:
    extensions: [gnome]
    command: usr/bin/gnome-text-editor
    desktop: usr/share/applications/org.gnome.TextEditor.desktop
    common-id: org.gnome.TextEditor.desktop
    environment:
      GTK_USE_PORTAL: "1"
      GDK_DEBUG: "portals"
    plugs:
      - home
      - removable-media
      - mount-observe
      - cups

parts:
  gnome-text-editor:
    plugin: nil
    source: .
    stage-packages:
     - gnome-text-editor
